= Projet Kotlin Aventure
:toc-title: Sommaire
:toc: top

Projet réalisé par : +
TRAN Nicolas +
MAUDET Dylan +
OKEMBA MEBOUKOU Cédrick

== Contexte +
KotlinAventure est un jeu de rôle d'aventure plonge les joueurs dans un monde fantastique rempli de monstres redoutables, de personnages héroïques et de combats épiques. +
Le jeu se déroule dans un univers médiéval-fantastique où les joueurs incarnent un personnage. +

Voici un aperçu des classes de personnages disponibles : +

Guerrier : Les guerriers sont des combattants puissants armés. Ils sont connus pour
leur force brute et leur capacité à infliger des dégâts élevés en combat. +

Voleur : Les voleurs excellent dans l'art de la discrétion et de la ruse. Ils sont capables de voler des objets précieux à leurs ennemis et de se faufiler dans les ombres pour échapper aux dangers. +

Mage : Les mages maîtrisent l'art de la magie et peuvent lancer des sorts
dévastateurs. Ils ont un grimoire rempli de sorts variés, chacun ayant un effet unique sur les adversaires.

== Introduction +

Ce projet a été réalisé en 2 sprint, le premier sprint était concentré sur la gestion des items et le deuxième sprint était concentré sur les fonctionnalités des classes.

Dans ce projet, nous devions réaliser plusieurs missions.

== Sprint 1

Dans le sprint 1, chaque mission est divisée en 6 étapes, et chaque étape est suivie d'une intermission au cours de laquelle les membres du groupe doivent échanger et expliquer le travail réalisé lors de l'étape aux autres membres du groupe. +

Le sprint 1 est divisé en 3 missions/branches. +

* - La branche 1 concerne principalement les armes.
* - La branche 2 concerne principalement les armures.
* - La branche 3 concerne principalement les potions et bombes.

=== Mission 1

==== Mission 1.1

La mission 1.1 consistait à modifier la méthode creerPersonnage() de la classe Jeu en faisant en sorte que : +

* L'utilisateur saisit le nom du personnage.
* L'utilisateur saisit les scores d'attaque, de défense, d'endurance et de vitesse (Attention l’utilisateur a un grand total de 40 points à répartir, si plus de 40 points sont distribués alors on recommence l’attribution des points).
* Les points de vie maximum sont calculés en fonction de l'endurance.
* Le personnage spécifique est créé.
* On valorise l’attribut joueur avec le personnage créé et on retourne le personnage.

[source,kotlin]

/**
     *  Méthode pour créer le personnage du joueur en demandant les informations à l'utilisateur
     *
     */
    fun creerPersonnage(): Personnage {
        println("Création votre personnage:")
        // TODO Mission 1.1
        val nomPerso = readln()
        var ptattaque: Int
        var ptdefense: Int
        var ptendurance: Int
        var ptvitesse: Int
 do {
            println("Veuillez attribuer vos points de statistique")
            println("Attaque : ")
            ptattaque= readln().toInt()
            println("Défense : ")
            ptdefense = readln().toInt()
            println("Endurance : ")
            ptendurance = readln().toInt()
            println("Vitesse : ")
            ptvitesse= readln().toInt()
            val pttotal: Int = ptattaque + ptdefense + ptendurance + ptvitesse
        }
            while (pttotal > 40)
            val pointDeVieMax = 50 + (10 * ptendurance)
            val hero = Personnage(nomPerso, pointDeVieMax, pointDeVieMax, 12, 8, 8, armePrincipale = epeeLongueDuDroit, armurePrincipale = cotteDeMaillesAdamantine , vitesse = 12)
            this.joueur = hero
            return  hero
    }
}

==== Mission 1.2

La mission 1.2 consistait à modifier la méthode tourDuJoueur() de la classe Jeu en faisant en sorte que :

* Le tour du Joueur commence, et l'annonce est affichée.
* Le joueur est invité à choisir une action parmi les options affichées : Attaquer, Passer, (d’autres actions seront disponibles plus tard).
* L'action choisie par le joueur est saisie.
* En fonction de l'action choisie, l'action correspondante est exécutée. Par exemple, si le joueur choisit d'attaquer, la méthode joueur.attaquer(monstre) est appelée.

[source,kotlin]
 // Méthode pour simuler un tour de combat du joueur
    fun tourDeJoueur() {
        println("\u001B[34m ---Tour de ${this.jeu.joueur.nom} (pv: ${this.jeu.joueur.pointDeVie}) ---")
       //TODO Mission 1.2
        //Choix de l'action
        println("Sélectionnez votre action ")
        var action = readln().toInt()
        if(action==0 ) {
            this.jeu.joueur.attaque(monstre)
            println("\u001b[0m")
        }else if (action ==1) {
                println("${this.jeu.joueur.nom} passe son tour")
            } else if (action == 2){
                this.jeu.joueur.boirePotion()
                println("${this.jeu.joueur.nom} Boit une potion")
        }
    }

==== Mission 1.2

La mission 1.2 consistait modifier la méthode tourDeMonstre en faisant en sorte que :

* Le tour du monstre commence, et l'annonce est affichée.
* Un nombre aléatoire est généré pour déterminer le comportement du monstre.
* Le résultat de la génération aléatoire est utilisé pour décider si le monstre va attaquer
le joueur ou passer.
* Si le monstre choisit d'attaquer le joueur ou de passer, l'action correspondante est
exécutée (par exemple, monstre.attaquer(joueur) ou une annonce de passage est
affichée).

Pour décider de l’action du monstre on tire un nombre aléatoire entre 1 et 100 :

* Si le nombre est inférieur ou égal à 70, le monstre attaque sinon le monstre passe son tour

[source,kotlin]
// Méthode pour simuler un tour de combat du monstre
    fun tourDeMonstre() {
        println("\u001B[31m---Tour de ${monstre.nom} (pv: ${monstre.pointDeVie}) ---")
        //TODO Mission 1.3
        if(TirageDes(1,100).lance() <= 70) {
            this.monstre.attaque(this.jeu.joueur)
            println("\u001b[0m")
        } else if (this.monstre.avoirPotion() && this.monstre.pointDeVie < this.monstre.pointDeVieMax / 2 && TirageDes(1,100).lance() <= 80) {
            this.monstre.boirePotion()
        } else {
            println("${monstre.nom} passe son tour")
        }
    }

== Intermission 1

L'intermission 1 nous demandait d'ajouter des monstres à la liste des monstres du jeu, voici un exemple :

[source,kotlin]

val gnoll = Personnage(
            "gnoll",
            pointDeVie = 25,
            pointDeVieMax = 25,
            attaque = 11,
            defense = 8,
            endurance = 11,
            armePrincipale = lanceDuKobold,
            armurePrincipale = null,
            vitesse = 14)

 //On ajoute les monstres a la liste de monstres du jeu
    val jeu = Jeu(listOf(gobelin,gnoll))

=== Mission 2

==== Mission 2.1

Cette mission demandait de réaliser les classes Arme et TypeArme +

===== La classe TypeArme

[source,kotlin]
class TypeArme (
     nom: String,
    val nombreDes: Int,
    val valeurDeMax: Int,
    val multiplicateurCritique:Int,
    val activationCritique:Int,
    )

===== La classe Arme
La classe Arme nous demandait de créer la méthode calculerDegats(), la méthode retourne un entier et calcule les dégâts en prenant en compte :

* Le tirage d'un dé qui vient de la méthode lance() de la classe TirageDes :
[source,kotlin]
class TirageDes(val nbDe:Int, val maxDe:Int) {
    fun lance():Int{
        // Si on lance 3d8
        // nbDe = 3 correspond au nombre de dés que l'on souhaite lancer
        // maxDe = 8 correspond au nombre de face du dé et aussi a la valeur maximum du dé
        // resultat =0
        // on lance le premier dé on fait un 4
        // resultat =4
        // on lance le deuxième dé on fait un 3
        // resultat =7
        // on lance le troisème dé on fait un 8
        // resultat = 15
        // la méthode retourne 15
        var resultat=0
        repeat(this.nbDe){
            resultat+=(1..this.maxDe).random()
        }
        return resultat
    }
}

* Un lancé autre dé et si le résultat est supérieur ou égal à l'attribut activationCritique du type d'arme alors les dégâts sont multipliés par le multiplicateurCritique du type d'arme. Si il y a un coup critique, le message "Critique" est affiché

[source,kotlin]
class Arme ( nom: String, description: String,val qualite: Qualite,val typeArme: TypeArme):Item(nom,description) {
    fun calculerDegats(): Int {
        val tirage = TirageDes(this.typeArme.nombreDes, this.typeArme.valeurDeMax)
        // Utilisation de la méthode lance() pour obtenir le résultat du lancé
        var resultat = tirage.lance()
        val tirageCrit = TirageDes(this.typeArme.nombreDes, this.typeArme.activationCritique)
        if(tirageCrit.lance() <= this.typeArme.activationCritique){
            var critique = resultat * this.typeArme.multiplicateurCritique
            var degatsTotal = critique + this.qualite.bonusRarete
            println("Critique")
            return degatsTotal
        } else{
            val degatsTotal = resultat + this.qualite.bonusRarete
            return degatsTotal
        }
    }

==== Mission 2.2

Cette Mission demandait de réaliser les classes Armure et TypeArmure

===== La classe TypeArmure

[source,kotlin]
class TypeArmure (
     nom: String,
    val bonusType: Int,
)

===== La classe Armure

La classe Armure nous demandait de créer la méthode calcule protection qui retourne un entier en prenant en compte :

* Le bonus de protection obtenu en additionnant le bonus type de l'armure et le bonusQualite de la qualité de l'armure

[source,kotlin]
class Armure (
        nom: String,
        description:String,
        val qualite: Qualite,
        val typeArmure: TypeArmure): Item(nom,description){
    fun calculeProtection(): Int{
        var additionProtection = this.typeArmure.bonusType + this.qualite.bonusRarete
        return additionProtection
    }


==== Mission 2.3

Cette mission demandait de réaliser les classes Potion et Bombe et la méthode utiliser()

===== La classe Potion

[source,kotlin]
class Potion (nom: String, var soin: Int, description: String): Item(nom,description){
    override fun utiliser(cible: Personnage) {
    }
}

===== La classe Bombe

[source,kotlin]
class Bombe ( nom: String, var nbDe: Int, var maxDe: Int, description: String):Item(nom,description) {
    override fun utiliser(cible: Personnage) {
        val tirage = TirageDes(nbDe, maxDe)
        val degats = tirage.lance()
        val protectionCible = cible.calculeDefense()
        val degatsFinaux = maxOf(degats - protectionCible, 1)
        cible.pointDeVie -= degatsFinaux
        println("La cible a pris $degatsFinaux dégâts.")
    }

}

=== Intermission 2

L'intermission 2 nous demande d'ajouter un attribut armrPrincipale et armure au personnage

=== Mission 3

==== Mission 3.1

Cette mission nous demande de faire un test unitaire pour la méthode calculerDegats()

[source,kotlin]

class ArmeTest {
@Test
    fun calculerDegats() {
        val arme = Arme("","",qualiteCommun,hache)
        var result=arme.calculerDegats()
        println(result)
        Assertions.assertTrue(result >=1)
        Assertions.assertTrue(result <=16)
    }
}

==== Mission 3.2

Cette mission nous demande de faire un test unitaire pour la méthode calculProtection()

[source,kotlin]

class ArmureTest {
    @Test
    fun calculeProtection() {
        val result = cotteDeMaillesAdamantine.calculeProtection()
        print(result)
        Assertions.assertEquals(6+1, result)
    }
}

==== Mission 3.3

Cette mission nous demande de faire un test unitaire pour la méthode utiliser() de la classe Bombe

[source,kotlin]

class BombeTest {
    @Test
    fun utiliserBombe() {
        val gobelin = Personnage(
            "gobelin",
            pointDeVie = 20,
            pointDeVieMax = 20,
            attaque = 5,
            defense = 4,
            endurance = 6,
            armePrincipale = lanceDuKobold,
            armurePrincipale = null,
            vitesse = 11)
        var result=bombeFlash.utiliser(gobelin)
        println(result)
        var dgt = gobelin.pointDeVie - 1
       Assertions.assertTrue(gobelin.pointDeVie<20)
    }
}

=== Mission 4

La mission demande de faire hériter les classes Arme, Armure , Bombe et Potion de la classe Item. +

Voici la classe Item :

[source,kotlin]

open class Item(val nom : String, val description: String) {
    open fun utiliser(cible: Personnage){
        println("$nom ne peut pas etre utilise.")
    }
    override fun toString(): String{
        return "${nom} (nom = '$nom', description = '$description')"
    }
}

Dans cette classe, le mot-clé "open" signifie que la classe est ouverte à l'héritage. +

Ce qui veut dire que nous pouvons retirer les val ou var devant les attributs nom et description provenant de la classe Item et nous indiquons l'héritage avec :Item(nom,description) +

Et nous ajoutons aussi override pour indiquer que nous souhaitons redéfinir une méthode déjà définie dans un parent/ancêtre

==== Mission 4.1

Cette mission demande de faire hériter la classe Arme de la classe Item

[source,kotlin]

class Arme ( nom: String, description: String,val qualite: Qualite,val typeArme: TypeArme):Item(nom,description)
...
override fun utiliser(cible: Personnage){

    }

==== Mission 4.2

Cette mission demande de faire hériter la classe Armure de la classe Item

[source,kotlin]

class Armure (
        nom: String,
        description:String,
        val qualite: Qualite,
        val typeArmure: TypeArmure): Item(nom,description){
...
    override fun utiliser(personnage: Personnage){
    }

==== Mission 4.3

Cette mission demande de faire hériter les classes Bombe et Potion de la classe Item

===== Bombe

[source,kotlin]

class Bombe ( nom: String, var nbDe: Int, var maxDe: Int, description: String):Item(nom,description) {

    override fun utiliser(cible: Personnage) {
        val tirage = TirageDes(nbDe, maxDe)
        val degats = tirage.lance()

        val protectionCible = cible.calculeDefense()
        val degatsFinaux = maxOf(degats - protectionCible, 1)

        cible.pointDeVie -= degatsFinaux

        println("La cible a pris $degatsFinaux dégâts.")
    }
}

===== Potion

[source,kotlin]

class Potion (nom: String, var soin: Int, description: String): Item(nom,description){
    override fun utiliser(cible: Personnage) {
    }

=== Mission 5

==== Mission 5.1

Cette mission demande de modifier les méthodes attaque() et de créer la méthode equipe() dans la classe Personnage

===== La méthode attaque()

Dans la modification de la méthode attaque() nous devons faire en sorte que :

* Le personnage vérifie s'il a une arme équipée. Si une arme est équipée, les dégâts de
base sont augmentés en fonction des dégâts de l'arme.

* Les dégâts sont calculés en combinant les dégâts de base du personnage et les dégâts
de l'arme (si une arme est équipée).

* Les dégâts sont ajustés en fonction de la défense de l'adversaire. Au minimum, au
moins 1 point de dégât est infligé.

* Les dégâts infligés à l'adversaire sont calculés.

* Les dégâts sont appliqués à l'adversaire en réduisant ses points de vie.

* Le résultat de l'attaque est affiché, indiquant quel personnage attaque avec quelle arme
(ou une attaque de base) et combien de points de dégâts sont infligés.

* Les dégâts de base sont équivalent au score d’attaque du personnage /2

* Si le personnage a une arme on ajoute aux dégâts de base les dégâts de l’arme
retourner par la méthode calculerDegat()

[source,kotlin]

// Méthode pour attaquer un adversaire
    fun attaque(adversaire: Personnage) {
        //TODO Mission 4.1
        var degats = this.attaque / 2
        if (armePrincipale != null) {
            degats += armePrincipale!!.calculerDegats()
        }
        degats-= adversaire.calculeDefense()
        if(degats<=1){
            degats=1
        }
        adversaire.pointDeVie -= degats
        println("$nom attaque ${adversaire.nom} avec une attaque de base et inflige $degats points de dégâts.")
    }

===== La méthode equipeArme()

Il existe deux versions de la méthode equipe() une méthode permet d’équiper une arme, l’autre
permet d’équiper une armure.

Ici c'est la méthode qui permet d'équiper une arme.

[source,kotlin]

 open fun equipeArme(armeEquipe: Arme) {
        if (armeEquipe in this.inventaire) {
            var armePrincipal = armeEquipe
            println("${this.nom} equipe ${armeEquipe.nom}")
        }
    }

===== Modification de la méthode utiliser() de la classe Arme

Nous appliquons une modification sur le corps de la méthode utiliser() de la classe qui consiste à ce que la cible(paramètre) équipe l'arme en utilisant la méthode equipeArme() de la classe Personnage.

[source,kotlin]

    override fun utiliser(cible: Personnage){
        cible.equipeArme(this)
    }

==== Mission 5.2

Cette mission demande de créer les méthodes calculDefense() et equipe() de la classe Personnage

===== La méthode calculDefense()

Cette méthode ne prend pas de paramètre et elle retourne un entier qui correspond à la défense total du personnage, pour cela il faut que :

* La défense de base correspond à la moitié du score du défense du personnage

* Si le personnage a une armure alors on ajoute le bonus de l’armure en utilisant la
méthode calculProtection()

* On retourne la valeur

[source,kotlin]

fun calculeDefense(): Int {
        //TODO Mission 4.2
        var result = this.defense / 2;
        if (this.armurePrincipale != null) {
            result = result + this.armurePrincipale!!.calculeProtection()
        }
        return result;
    }

===== La méthode equipe()

Contrairement à la mission 5.1, ici cette méthode permet d'équiper une armure. +
La méthode prend en paramètre une armure.

* Si l'armure (paramètre) est dans l’inventaire du personnage alors l’attribut armure du personnage
prend la valeur du paramètre.

* On affiche le message « nomPerso equipe nomArmure »

[source,kotlin]

fun equipeArmure(armureEquipe: Armure) {
        if (armureEquipe in this.inventaire) {
            var armurePrincipal = armureEquipe
            println("${this.nom} equipe ${armureEquipe.nom}")
        }
    }

==== Mission 5.3

Cette mission demande de créer les méthodes avoirPotion(), avoirBombe(), boirePotion() de la classe Personnage.

===== La méthode avoirPotion()

Cette méthode ne prend pas de paramètre et retourne un Booléen.

* Retourne vrai si le personnage dispose au moins d’une potion dans son inventaire sinon elle retourne
faux.

[source,kotlin]

fun avoirPotion(): Boolean {
        for (item in this.inventaire) {
            if (item is Potion) {
                return true
            }
        }
        return false
    }

===== La méthode avoirBombe()

Cette méthode a le même principe que pour la méthode avoirPotion()

[source,kotlin]

fun avoirBombe(): Boolean {
        for (item in this.inventaire) {
            if (item is Bombe) {
                return true
            }
        }
        return false
    }

===== La méthode boirePotion()

La méthode ne prend pas de paramètre et ne retourne rien.

Pour réaliser cette méthode il faut que :

* Le personnage récupère la première potion de la liste (s'il y en a).

* Le personnage récupère le montant de soin de la potion.

* Le personnage met à jour ses points de vie en ajoutant le montant de soin de la potion. Si
les points de vie dépassent le maximum, ils sont ajustés au maximum.

* Le personnage retire la potion de son inventaire.

* Le résultat de la boisson de la potion est affiché, indiquant le nom de la potion et le
montant de points de vie récupérés.

[source,kotlin]

    fun boirePotion() {
        if (avoirPotion() == true) {
            var premierePotion = -1
            for (i in 0..this.inventaire.lastIndex) {
                if (this.inventaire[i] is Potion) {
                    val potion: Potion = this.inventaire[i] as Potion
                    premierePotion = potion.soin
                    this.inventaire.remove(potion)
                    break
                }
            }
            pointDeVie += premierePotion
            if (pointDeVie > pointDeVieMax) {
                this.pointDeVie = pointDeVieMax
            }
            println("Vous êtes maintenant à $pointDeVie grâce à l'usage de la potion.")
        }
    }

=== Missionn 6

==== Mission 6.1

La mission demande créer les méthodes afficheInventaire() et loot() de la classe Personnage

===== La méthode afficheInventaire()

Cette méthode ne prend pas de paramètre et ne retourne rien.

Il faut que cette méthode :

* Afficher le message « inventaire de nomPerso »

* Afficher chaque item de l’inventaire du personnage. A chaque item est associé un numéro (son index
dans l’inventaire).
Par exemple : +
0 => Potion de soin +
1 => Epée longue Legendaire

[source,kotlin]

fun afficheInventaire(){
        println("inventaire de ${this.nom}")
        for (i in 0..this.inventaire.lastIndex) {
            println(this.inventaire[i])
        }
    }

===== La méthode loot()

La méthode prend une cible de type Personnage en paramètre et ne retourne rien.

La méthode doit :

* Vérifier que la cible a des pv inférieure ou égale à 0.

* Si c’est le cas on remplace l’arme principale de la cible par null et son armure par null et on transfère
son inventaire a l’objet courant (on ajoute l’inventaire de la cible a l’objet courant).

[source,kotlin]

fun loot(cible: Personnage){
        if (cible.pointDeVie <= 0){
            cible.armePrincipale = null
            cible.armurePrincipale = null
            this.inventaire.addAll(cible.inventaire)
            cible.inventaire = mutableListOf()
        }
    }

== Sprint 2

Ce sprint a pour objectif d'ajouter comme fonctionnalité le choix de la classe pour le personnage du joueur :

*  Le guerrier possède 2 armes.

*   Le voleur peut voler un objet, y compris une arme ou une armure, à l'ennemi.

*  Le mage peut lancer des sorts.

Les classes Guerrier, Voleur et Mage hérite de Personnage. +
Cela signifie que les "enfants" vont hériter des méthodes et attributs du parent. +
Cependant, il est toujours possible de redéfinir des méthodes déjà définies dans la classe parent, si nécessaire. +
Par exemple, la méthode "attaque()" peut rester la même pour un Voleur ou un Mage, mais un Guerrier pourrait utiliser ses deux armes.


=== Mission 7

==== Mission 7.1

Cette mission a pour but de créer la classe Guerrier en utilisant l'héritage

[source, kotlin]

class Guerrier(
    nom: String,
    pointDeVie: Int,
    pointDeVieMax: Int,
    attaque: Int,
    defense: Int,
    endurance: Int,
    vitesse: Int,
    armePrincipale: Arme?,
    armurePrincipale: Armure?,
    var armeSecondaire: Arme?
): Personnage(nom, pointDeVie, pointDeVieMax, attaque, defense, endurance, vitesse, armePrincipale, armurePrincipale ) {

==== Mission 7.2

Cette mission a pour but de créer la classe Voleur en utilisant l'héritage

[source, kotlin]

class Voleur(
    nom: String,
    pointDeVie: Int,
    pointDeVieMax: Int,
    attaque: Int,
    defense: Int,
    endurance: Int,
    vitesse: Int,
    armePrincipale: Arme?,
    armurePrincipale: Armure?,
) : Personnage(nom, pointDeVie, pointDeVieMax, attaque, defense, endurance, vitesse, armePrincipale, armurePrincipale){

==== Mission 7.3

Cette mission a pour but de créer les classes mage et sort en utilisant l'héritage

===== Mage
[source, kotlin]

class Mage(
    nom: String,
    pointDeVie: Int,
    pointDeVieMax: Int,
    attaque: Int,
    defense: Int,
    endurance: Int,
    vitesse: Int,
    armePrincipale: Arme?,
    armurePrincipale: Armure?
) : Personnage(nom, pointDeVie, pointDeVieMax, attaque, defense, endurance, vitesse, armePrincipale, armurePrincipale ) {

===== Sort

[source,kotlin]

class Sort(val nom:String, val effet :(Personnage,Personnage)-> Unit) {
}

=== Mission 8

==== Mission 8.1

Cette mission demande de créer les méthodes equipe() et attaquer() de la classe Guerrier

===== La méthode equipeArme()

Quand un guerrier équipe une arme, il doit choisir l’emplacement de l’arme (principale ou secondaire).

[source,kotlin]

override fun equipeArme(armeEquipe: Arme) {
        if (armeEquipe in this.inventaire) {
            var armePrincipal = armeEquipe
            println("${this.nom} equipe ${armeEquipe.nom}")
        }
    }
}

===== La méthode attaquer()

Un guerrier attaque avec ces deux armes il faut donc redéfinir la méthode attaque()

[source,kotlin]

fun attaquer(adversaire: Personnage) {
        var degats = 0
        if (armePrincipale != null) {
            degats += attaque + armePrincipale!!.calculerDegats()
        }
        if (armeSecondaire != null) {
            degats += attaque + armeSecondaire!!.calculerDegats()
        }
        // Soustraction de la défense de l'adversaire
        degats -= adversaire.calculeDefense()
        // Vérification si les dégâts sont positifs
        if (degats > 0) {
            adversaire.pointDeVie -= degats
            println("$nom attaque ${adversaire.nom} et inflige $degats points de dégâts.")
        } else {
            println("$nom attaque ${adversaire.nom} mais ne fait aucun dégât.")
        }
    }

==== Mission 8.2

Cette mission demande de créer la méthode voler() de la classe Voleur

La méthode voler() prend en paramètre une cible de type Personnage.

* Vole un item de son inventaire tiré aléatoirement.

* Dans le cas où le voleur vole une arme ou une armure qui est équipé par la cible, il faut la retirer de l'attribut arme ou armure.

[source,kotlin]

    fun volerItem(cible: Personnage){
        if (cible.inventaire.size > 0) {
            val indexAleatoire = (0..cible.inventaire.size).random()
            val itemVole = cible.inventaire.removeAt(indexAleatoire)
            println("L'action a été réalisée avec succès ! Vous avez volé $itemVole à l'ennemi.")
            this.inventaire.add(itemVole)
            if (itemVole == cible.armePrincipale) {
                cible.armePrincipale == null
            } else if (itemVole == armurePrincipale) {
                cible.armurePrincipale == null
            }
        } else {
            println("Aucun objet n'a été volé haha cheh ratio.")
        }
    }

==== Mission 8.3

Cette mission demande de créer les méthodes afficherGrimoire() et choisirEtlancerSort() de la classe Mage

===== La méthode afficherGrimmoire()

Le grimoire est une liste mutable de sort. +
La méthode afficherGrimmoire() affiche tous les sorts présents dans le grimoire et l’index du sort : +
0 => Boule de feu +
1=> Sort de soins

[source,kotlin]

fun afficheGrimoire() {
        println("Sorts de ${this.nom} :")
        for (sort in grimoire) {
            if (sort is Sort) {
                println("- ${sort.nom}")
            }
        }
    }

===== La méthode choisirEtLancerSort()

La méthode invoque la méthode afficherGrimoire puis demande à l'utilisateur de lancer un sort. +
Si le choix de l’utilisateur est valide alors on demande à l’utilisateur de choisir la cible du sort : le joueur ou le monstre.
Puis lance l’effet du sort : sortChoisi.effet(this,cible). +
Le premier argument correspond au lanceur de sort. +
Le deuxième argument à la cible.

[source,kotlin]

fun chosirEtLancerSort(ennemi:Personnage) {
        if(grimoire.isEmpty()){
            print("Le grimoire est vide. Vous ne pouvez pas lancer de sort")
        } else{
            println(this.afficheGrimoire())
            println("Choix de sort : ")
            var indexSort = readln().toInt()
            if(this.grimoire.size<=indexSort)
            {
            var sort = this.grimoire[indexSort]
                var personnage = this
                var adversaire = ennemi
                println("Selectionnez votre cible :")
                println(" [0] => Personnage, [1] Ennemi")
                var cible = readln().toInt()
                if(cible == 0 || cible ==1){
                    if(cible == 0 ){
                    sort.effet(personnage,personnage)
                } else if(cible == 1){
                        sort.effet(personnage,adversaire)
                    }                }
            } else {
                println("Choix de sort invalide")
            }
        }
    }

=== Mission 9

==== Mission 9.1

Cette mission demande de créer les sorts Boule de feu et Missile magique à partir du Main

===== Boule de feu

[source,kotlin]

val bouleDeFeu = Sort("Boule de feu", { caster, cible  ->
    run {
        val degatsCaster = caster.attaque/3
        val tirageDes = TirageDes(1,6)
        var degat = tirageDes.lance()
        degat+= degatsCaster
        degat -= cible.calculeDefense()
        cible.pointDeVie -= degat
        println("Boule de feu inflige $degat à ${cible.nom} ")
    }
})

===== Missile magique

[source,kotlin]

val missileMagique = Sort("Missile magique", { caster, cible ->
    run {
        val degatsCaster = caster.attaque/2
        val tirageDes = TirageDes(1,6)
        var compteur = 0
        if (compteur<degatsCaster){
            var degat = tirageDes.lance()
            degat -= cible.calculeDefense()
            cible.pointDeVie -= degat
            println("Le projectile magique inflige $degat à ${cible.nom} ")
            compteur += 1
        }
    }
})

==== Mission 9.2

Cette mission demande de créer les sorts Invocation d'une arme magique et Invocation d'une armure magique à partir du Main.

===== Invocation d'une arme magique

[source.kotlin]

val invocationArmeMagique = Sort("Invocation d'arme magique", { caster, cible ->
run {
val tirageDes = TirageDes(1, 20)
val resultatTirage = tirageDes.lance()
var qualite: Qualite? = null
    when{
        resultatTirage < 5 -> qualite = qualiteCommun
        resultatTirage < 10 -> qualite = qualiteRare
        resultatTirage < 15 -> qualite = qualiteEpic
        else -> {
            qualite = qualiteLegendaire
        }
    }
    val armeMagique = Arme("Arme magique", "une arme magique invoquée via un sort", qualite, epeeLongue)
    caster.inventaire.add(armeMagique)
    caster.equipeArme(armeMagique)
     println("L'arme magique à été ajoutée à l'inventaire.")
    }
})

===== Invocation d'une armure magique

[source,kotlin]

val invocationArmureMagique = Sort("Invocation armure magique", { caster, cible ->
    run {
        val tirageDes = TirageDes(1, 20)
        val resultatTirage = tirageDes.lance()
        var qualite: Qualite? = null
        when{
            resultatTirage < 5 -> qualite = qualiteCommun
            resultatTirage < 10 -> qualite = qualiteRare
            resultatTirage < 15 -> qualite = qualiteEpic
            else -> {
                qualite = qualiteLegendaire
            }
        }
        val armureMagique = Armure("Armure magique", "une armure magique invoquée via un sort", qualite, cuir)
        caster.inventaire.add(armureMagique)
        caster.equipeArmure(armureMagique)
        println("L'armure magique à été ajoutée à l'inventaire.")
    }
})

==== Mission 9.3

Cette mission demande de créer le sort de soin.

[source,kotlin]

val sortDeSoin = Sort("Sort de soin",{ caster, cible ->
    run {
        val tirageDes = TirageDes (1,6)
        val scoreAttaque = caster.attaque/2
        var soin = tirageDes.lance()+ scoreAttaque
        caster.pointDeVie += soin
        if(caster.pointDeVie>caster.pointDeVieMax){
            val soinProcure = caster.pointDeVieMax - caster.pointDeVie
            caster.pointDeVie=caster.pointDeVieMax
            println("Sort de soin a soigné ${caster.nom} de $soinProcure pv")
        } else{
            println("Sort de soin a soigné ${caster.nom} de $soin pv")
        }
    }
})

== Conclusion

Ce projet nous a permis tout d'abord de renforcer nos compétence et d'apprendre de nouvelles choses sur le langage de programmation Kotlin. +
Il nous a permis aussi de travailler en équipe, de se partager les tâches et de communiquer ensemble.




